require 'spec_helper'

describe Mallow::Fluffer do

  before { @fluffer = Mallow::Fluffer.new [] }

  describe '#fluff' do
    it 'maps #fluff_one over its arguments' do
      data = %w{ me i like a good american made hot dog time to time }
      data.each {|word| @fluffer.should_receive(:fluff_one).with word }
      @fluffer.fluff(data).should == data.map {nil}
    end
  end

  describe '#fluff_one' do
    context 'with rules' do
      before do
        @fluffer = Mallow.fluff do |match|
          match.an(Array).to {1}
          match.a(Hash).to {2}
        end
      end
      it "executes the fluffer's rules on its argument until one matches" do
        @fluffer.fluff_one([1]).should == 1
        @fluffer.fluff_one({a:1}).should == 2
      end
      it "raises an exception if no rule matches" do
        expect { @fluffer.fluff_one(1) }.to raise_error Mallow::Fluffer::DeserializationException
      end
    end
  end

  describe '::build' do
    it 'returns a new Mallow::Fluffer with rules generated by Mallow::Rule::Builder' do
      Mallow::Rule::Builder.should_receive(:build).and_return []
      Mallow::Fluffer.build.should be_an_instance_of Mallow::Fluffer
    end
  end

end

